<?php
/**
 * Nexora Engine — Advanced Cache Drop-In (Network Edition v2.0.0)
 *
 * Auto-generated by Nexora Engine (NEXENG_Dropin::install()).
 * DO NOT EDIT MANUALLY — this file is overwritten by Nexora Engine.
 *
 * This variant serves WordPress multisite networks. It loads a small PHP
 * config map (ncx-network-map.php) that maps host+path → static_root for
 * each enrolled site, then falls through to the single-site serve logic.
 *
 * @nexora-dropin
 * @signature 6f3a1c
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

$start_time = microtime(true);

if ( ! function_exists( 'nexeng_static_html_cache_control' ) ) {
    function nexeng_static_html_cache_control(): string {
        return 'public, max-age=300, s-maxage=3600, stale-while-revalidate=86400, must-revalidate';
    }
}

if ( ! function_exists( 'nexeng_static_runtime_sync_html' ) ) {
    function nexeng_static_runtime_sync_html( string $html, string $build_id, string $home_prefix ): string {
        if ( $build_id === '' ) { return $html; }
        $html = preg_replace_callback(
            '/\b(href|src)=(["\'])([^"\']+\.(?:css|js)(?:\?[^"\']*)?)\2/i',
            static function ( array $m ) use ( $build_id ): string {
                $url = html_entity_decode( $m[3], ENT_QUOTES, 'UTF-8' );
                if ( preg_match( '#^(?:data|blob):#i', $url ) ) { return $m[0]; }
                // phpcs:ignore WordPress.WP.AlternativeFunctions.parse_url_parse_url -- Network drop-in executes before WordPress loads; wp_parse_url() is undefined here, native parse_url() required.
                $parts = parse_url( $url );
                $path  = is_array( $parts ) && isset( $parts['path'] ) ? (string) $parts['path'] : $url;
                if ( ! preg_match( '/\.(?:css|js)$/i', $path ) || strpos( $path, '/_ncx/' ) !== false ) { return $m[0]; }
                $fragment = '';
                if ( strpos( $url, '#' ) !== false ) {
                    [ $url, $fragment ] = explode( '#', $url, 2 );
                    $fragment = '#' . $fragment;
                }
                $url = preg_replace( '/([?&])ver=[^&]*/i', '$1ver=' . rawurlencode( $build_id ), $url, 1, $count );
                if ( ! $count ) { $url .= ( strpos( $url, '?' ) === false ? '?' : '&' ) . 'ver=' . rawurlencode( $build_id ); }
                return $m[1] . '=' . $m[2] . htmlspecialchars( str_replace( '?&', '?', $url ) . $fragment, ENT_QUOTES, 'UTF-8' ) . $m[2];
            },
            $html
        );
        $meta = '<meta name="ncx-build" content="' . htmlspecialchars( $build_id, ENT_QUOTES, 'UTF-8' ) . '">';
        $html = preg_match( '/<meta[^>]+name=["\']ncx-build["\'][^>]*>/i', $html )
            ? preg_replace( '/<meta[^>]+name=["\']ncx-build["\'][^>]*>/i', $meta, $html, 1 )
            : preg_replace( '/(<\/head>)/i', $meta . '$1', $html, 1 );
        if ( strpos( $html, 'ncx-runtime-sync' ) !== false ) { return $html; }
        $script = '<script id="ncx-runtime-sync">(function(){var b=' . json_encode( $build_id ) . ';try{localStorage.setItem("nexeng_build_id",b)}catch(e){}window.NEXENG_BUILD_ID=b;})();</script>';
        return preg_replace( '/(<\/head>)/i', $script . '$1', $html, 1 );
    }

    function nexeng_static_html_valid( string $html, string $build_id = '' ): bool {
        if ( strlen( $html ) < 200 || stripos( $html, '</html>' ) === false ) { return false; }
        if ( stripos( $html, '<html' ) === false && stripos( $html, '<!doctype' ) === false ) { return false; }
        if ( $build_id !== '' && strpos( $html, 'name="ncx-build"' ) === false ) { return false; }
        return true;
    }

    function nexeng_static_variant_path( string $static_root, string $real_file, string $build_id, int $mtime ): string {
        $root = rtrim( str_replace( '\\', '/', $static_root ), '/' );
        $file = str_replace( '\\', '/', $real_file );
        $rel  = ltrim( substr( $file, strlen( $root ) ), '/' );
        $key  = substr( md5( $rel . '|' . $build_id . '|' . $mtime ), 0, 16 );
        return dirname( $static_root ) . '/nexora-private/ncx-sync/' . $key . '.html';
    }

    function nexeng_static_cleanup_variants( string $static_root ): void {
        $dir = dirname( $static_root ) . '/nexora-private/ncx-sync';
        // phpcs:ignore WordPress.WP.AlternativeFunctions.rand_mt_rand -- Drop-in runs before WP loads pluggable.php, so wp_rand() is unavailable; only a non-cryptographic 1-in-100 sampling probe.
        if ( ! is_dir( $dir ) || mt_rand( 1, 100 ) !== 1 ) { return; }
        $now = time();
        foreach ( glob( $dir . '/*' ) ?: [] as $file ) {
            if ( is_file( $file ) && ( substr( $file, -4 ) === '.tmp' || $now - (int) @filemtime( $file ) > 172800 ) ) {
                // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- Network drop-in (advanced-cache-network.php) executes before WP loads; WP_Filesystem is unavailable here.
                @unlink( $file );
            }
        }
    }

    function nexeng_static_synchronized_body( string $static_root, string $real_file, string $build_id, string $home_prefix, int $mtime ) {
        $variant = nexeng_static_variant_path( $static_root, $real_file, $build_id, $mtime );
        if ( is_file( $variant ) && (int) @filemtime( $variant ) >= $mtime ) {
            $cached = @file_get_contents( $variant );
            if ( is_string( $cached ) && nexeng_static_html_valid( $cached, $build_id ) ) { return $cached; }
        }
        $source = @file_get_contents( $real_file );
        if ( ! is_string( $source ) || ! nexeng_static_html_valid( $source ) ) { return false; }
        $synced = nexeng_static_runtime_sync_html( $source, $build_id, $home_prefix );
        if ( ! nexeng_static_html_valid( $synced, $build_id ) ) { return false; }
        $dir = dirname( $variant );
        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- Network drop-in (advanced-cache-network.php) executes before WP loads; WP_Filesystem is unavailable here.
        if ( ! is_dir( $dir ) ) { @mkdir( $dir, 0755, true ); }
        if ( is_dir( $dir ) ) {
            $deny = dirname( $dir ) . '/.htaccess';
            if ( ! file_exists( $deny ) ) { @file_put_contents( $deny, "Order deny,allow\nDeny from all\n" ); }
            // phpcs:ignore WordPress.WP.AlternativeFunctions.rand_mt_rand -- Drop-in runs before WP loads pluggable.php; mt_rand() only salts a temp filename, no security dependence.
            $tmp = $variant . '.tmp.' . substr( md5( microtime( true ) . mt_rand() ), 0, 8 );
            if ( @file_put_contents( $tmp, $synced, LOCK_EX ) !== false ) {
                // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename -- Network drop-in (advanced-cache-network.php) executes before WP loads; WP_Filesystem is unavailable here. Atomic variant publish.
                @rename( $tmp, $variant );
                // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_touch -- Network drop-in (advanced-cache-network.php) executes before WP loads; WP_Filesystem is unavailable here.
                @touch( $variant, max( time(), $mtime ) );
            } else {
                // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- Network drop-in (advanced-cache-network.php) executes before WP loads; WP_Filesystem is unavailable here.
                @unlink( $tmp );
            }
        }
        nexeng_static_cleanup_variants( $static_root );
        return $synced;
    }
}

(function () use ( $start_time ) {

    // ─── Fast skip checks (cheapest first) ───────────────────────────────────

    // 0. Master kill switch. See advanced-cache.php for the full rationale:
    // this file runs before WordPress, so the "Static Delivery off" option is
    // unreadable here and only a filesystem marker can stop the mirror being
    // served. Absence of the marker means serve, so upgrades stay working.
    if ( @is_file( '__NEXENG_PRIVATE_DIR__/ssg-disabled.flag' ) ) { return; }

    // 1. GET only.
    if ( 'GET' !== nexeng_dropin_server( 'REQUEST_METHOD', 'GET', 10 ) ) { return; }

    // 2. Any query string disables the cache, except Nexora's own sync probe.
    $query_string = nexeng_dropin_server( 'QUERY_STRING' );
    if ( $query_string !== '' && ! preg_match( '/^nexeng_sync=[a-z0-9]+$/i', $query_string ) ) { return; }

    // 3. Skip authenticated users.
    if ( ! empty( $_COOKIE ) ) {
        foreach ( $_COOKIE as $k => $v ) {
            if ( strncmp( $k, 'wordpress_logged_in_', 20 ) === 0 ) { return; }
            if ( strncmp( $k, 'wp-postpass_',          12 ) === 0 ) { return; }
            if ( strncmp( $k, 'comment_author_',       15 ) === 0 ) { return; }
            if ( strncmp( $k, 'woocommerce_items_in_cart', 25 ) === 0 ) { return; }
            if ( $k === 'wp_woocommerce_session_' ) { return; }
        }
    }

    // 4. Resolve URI.
    // phpcs:ignore WordPress.WP.AlternativeFunctions.parse_url_parse_url -- Network drop-in executes before WordPress loads; wp_parse_url() is undefined here, native parse_url() required.
    $uri = parse_url( nexeng_dropin_server( 'REQUEST_URI', '/' ), PHP_URL_PATH );
    if ( ! is_string( $uri ) || $uri === '' ) { return; }

    // 5. Skip WP system / API / admin paths.
    if ( preg_match(
        '#^(?:/[^/]+)?/(wp-admin|wp-login\.php|wp-cron\.php|wp-json|wp-content|wp-includes|xmlrpc\.php)#i',
        $uri
    ) ) { return; }

    // 6. Skip URLs with file extensions.
    if ( preg_match( '#\.[a-zA-Z0-9]{2,5}$#', $uri ) ) { return; }

    // ─── Network site resolution ──────────────────────────────────────────────

    // Load the network map — a plain PHP array of site entries built by
    // NEXENG_Multisite::rebuild_network_map(). The map lives in a private,
    // .htaccess-protected directory so it cannot be downloaded via HTTP.
    $map_file = __NEXENG_MAP_FILE__;

    $static_root = '';
    $home_prefix = '';

    if ( is_file( $map_file ) ) {
        $nexeng_map = @include $map_file;

        if ( is_array( $nexeng_map ) && ! empty( $nexeng_map ) ) {
            $request_host = strtolower( nexeng_dropin_server( 'HTTP_HOST', '', 253 ) );
            // Strip port if present (e.g. localhost:8080 → localhost).
            $request_host = preg_replace( '/:[\d]+$/', '', $request_host );

            // Match: host must match AND (path must match OR path is empty).
            // Longer path matches take priority over shorter ones.
            $best_len  = -1;
            $best_root = '';
            $best_pref = '';

            foreach ( $nexeng_map as $site ) {
                if ( ! isset( $site['host'], $site['path'], $site['root'] ) ) { continue; }
                $site_host = strtolower( (string) $site['host'] );
                $site_path = rtrim( (string) $site['path'], '/' );

                if ( $site_host !== $request_host ) { continue; }

                // Path match: URI must start with site_path (or site_path is empty).
                if ( $site_path === '' || strpos( $uri, $site_path . '/' ) === 0 || $uri === $site_path ) {
                    if ( strlen( $site_path ) > $best_len ) {
                        $best_len  = strlen( $site_path );
                        $best_root = (string) $site['root'];
                        $best_pref = (string) ( $site['prefix'] ?? $site_path );
                    }
                }
            }

            if ( $best_root !== '' ) {
                $static_root = str_replace( '\\', '/', $best_root );
                $home_prefix = $best_pref;
            }
        }
    }

    // Fallback: use the baked-in single-site values for backward compat.
    if ( $static_root === '' ) {
        $static_root = str_replace( '\\', '/', '__NEXENG_STATIC_ROOT__' );
        $home_prefix = '__NEXENG_HOME_PREFIX__';
    }

    // ─── High-Speed Asset Streamer ────────────────────────────────────────────
    if ( strpos( $uri, '/_ncx_v12/' ) !== false ) {
        $map = [
            '/_ncx_v12/assets/ep/'          => '__NEXENG_CONTENT_REL__/plugins/elementor-pro/',
            '/_ncx_v12/assets/e/'           => '__NEXENG_CONTENT_REL__/plugins/elementor/',
            '/_ncx_v12/assets/t/'           => '__NEXENG_CONTENT_REL__/themes/',
            '/_ncx_v12/assets/uploads/ncx/' => '__NEXENG_CONTENT_REL__/uploads/elementor/',
            '/_ncx_v12/assets/'             => '__NEXENG_CONTENT_REL__/',
            '/_ncx_v12/lib/'                => '__NEXENG_INC_REL__/',
        ];
        $asset_path = null;
        foreach ( $map as $virtual => $real ) {
            if ( strpos( $uri, $virtual ) !== false ) {
                $rel_path   = substr( $uri, strpos( $uri, $virtual ) + strlen( $virtual ) );
                $asset_path = ABSPATH . $real . $rel_path;
                break;
            }
        }
        if ( $asset_path && is_file( $asset_path ) ) {
            $real_asset = realpath( $asset_path );
            $_nexeng_abspath_fwd = rtrim( str_replace( '\\', '/', ABSPATH ), '/' );
            if ( $real_asset && strncmp( str_replace( '\\', '/', $real_asset ), $_nexeng_abspath_fwd . '/', strlen( $_nexeng_abspath_fwd ) + 1 ) !== 0 ) {
                $real_asset = false;
            }
            if ( $real_asset ) {
                $ext   = strtolower( pathinfo( $real_asset, PATHINFO_EXTENSION ) );
                $mimes = [
                    'css' => 'text/css', 'js' => 'application/javascript',
                    'png' => 'image/png', 'jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg',
                    'gif' => 'image/gif', 'svg' => 'image/svg+xml', 'webp' => 'image/webp',
                    'ico' => 'image/x-icon', 'woff' => 'font/woff', 'woff2' => 'font/woff2',
                    'ttf' => 'font/ttf',
                ];
                @header_remove( 'X-Powered-By' );
                header( 'Content-Type: ' . ( $mimes[ $ext ] ?? 'application/octet-stream' ) );
                header( 'Cache-Control: public, max-age=31536000, immutable' );
                header( 'X-Nexora-Asset: HIT' );
                header( 'Content-Length: ' . filesize( $real_asset ) );
                // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_readfile -- Network drop-in (advanced-cache-network.php) executes before WP loads; WP_Filesystem is unavailable here. Streams an asset on the serve path.
                readfile( $real_asset );
                exit;
            }
        }
    }

    // ─── Resolve target static file ───────────────────────────────────────────

    if ( $static_root === '' || ! is_dir( $static_root ) ) { return; }

    // Strip site path prefix from URI before file lookup.
    $lookup_uri = $uri;
    if ( $home_prefix !== '' && strpos( $lookup_uri, $home_prefix ) === 0 ) {
        $lookup_uri = substr( $lookup_uri, strlen( $home_prefix ) );
        if ( $lookup_uri === '' ) { $lookup_uri = '/'; }
    }

    $slug = trim( $lookup_uri, '/' );
    $file = $slug === ''
        ? $static_root . '/index.html'
        : $static_root . '/' . $slug . '/index.html';

    // Path-traversal guard (normalize to forward slashes for cross-platform).
    $real_root = realpath( $static_root );
    $real_file = realpath( $file );
    if ( ! $real_root || ! $real_file ) { return; }
    $_nexeng_fwd_root = rtrim( str_replace( '\\', '/', $real_root ), '/' );
    $_nexeng_fwd_file = str_replace( '\\', '/', $real_file );
    if ( strncmp( $_nexeng_fwd_file, $_nexeng_fwd_root . '/', strlen( $_nexeng_fwd_root ) + 1 ) !== 0 ) { return; }
    if ( ! is_file( $real_file ) ) { return; }

    // ─── Conditional response (304) ───────────────────────────────────────────

    $mtime         = (int) filemtime( $real_file );
    $manifest_file = $static_root . '/manifest.json';
    $build_id      = 'nexeng_build_' . $mtime;
    if ( is_file( $manifest_file ) ) {
        $manifest_raw = @file_get_contents( $manifest_file );
        $manifest     = is_string( $manifest_raw ) ? json_decode( $manifest_raw, true ) : null;
        if ( is_array( $manifest ) && ! empty( $manifest['build_id'] ) ) {
            $build_id = preg_replace( '/[^a-zA-Z0-9_\-]/', '', (string) $manifest['build_id'] );
        }
    }
    $body          = nexeng_static_synchronized_body( $static_root, $real_file, $build_id, $home_prefix, $mtime );
    if ( ! is_string( $body ) ) { return; }
    $etag          = '"ncx-' . substr( md5( $body ), 0, 16 ) . '"';
    $last_modified = gmdate( 'D, d M Y H:i:s', $mtime ) . ' GMT';

    $client_etag = isset( $_SERVER['HTTP_IF_NONE_MATCH'] )     ? trim( nexeng_dropin_server( 'HTTP_IF_NONE_MATCH', '', 256 ) )     : '';
    $client_lm   = isset( $_SERVER['HTTP_IF_MODIFIED_SINCE'] ) ? trim( nexeng_dropin_server( 'HTTP_IF_MODIFIED_SINCE', '', 128 ) ) : '';

    $norm_client_etag = ( strncmp( $client_etag, 'W/', 2 ) === 0 ) ? substr( $client_etag, 2 ) : $client_etag;
    if ( $norm_client_etag === $etag ) {
        http_response_code( 304 );
        header( 'ETag: ' . $etag );
        header( 'Last-Modified: ' . $last_modified );
        header( 'Cache-Control: ' . nexeng_static_html_cache_control() );
        header( 'X-Robots-Tag: index, follow', true );
        header( 'X-Nexora-Cache: 304' );
        exit;
    }

    // ─── 200 OK — stream static file ─────────────────────────────────────────

    @header_remove( 'X-Powered-By' );
    @header_remove( 'X-Pingback' );
    @header_remove( 'Link' );

    header( 'Content-Type: text/html; charset=UTF-8' );
    header( 'Content-Length: ' . strlen( $body ) );
    header( 'ETag: ' . $etag );
    header( 'Last-Modified: ' . $last_modified );
    header( 'Cache-Control: ' . nexeng_static_html_cache_control() );
    header( 'X-Nexora-Cache: HIT' );
    header( 'X-Powered-By: Next.js' );
    header( 'X-Nextjs-Cache: HIT' );
    header( 'X-Content-Type-Options: nosniff' );
    header( 'Referrer-Policy: strict-origin-when-cross-origin' );
    header( 'X-Robots-Tag: index, follow', true );

    $raw_ua   = nexeng_dropin_server( 'HTTP_USER_AGENT', '', 255 );
    $clean_ua = substr( preg_replace( '/[^\x20-\x7E]/', '', $raw_ua ), 0, 200 );
    $log_entry = json_encode( [
        'url'     => $uri,
        'hit_type'=> 'hit',
        'ttfb'    => max( 1, (int) round( ( microtime( true ) - $start_time ) * 1000 ) ),
        'ip'      => nexeng_dropin_server( 'REMOTE_ADDR', '', 45 ),
        'ua'      => $clean_ua,
        'ts'      => time(),
    ] ) . "\n";

    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Drop-in serve path: $body is the cached static HTML page streamed verbatim to the browser; intentional full-page HTML, escaping would break it.
    echo $body;

    @ob_flush();
    flush();

    // Non-blocking log write.
    // Baked in at install time from wp_upload_dir(): the uploads directory is
    // configurable, WP_CONTENT_DIR can point anywhere, and on multisite each
    // site has its own - none of which this file can work out for itself,
    // because it runs before WordPress loads.
    $log_dir  = '__NEXENG_PRIVATE_DIR__';
    $log_file = $log_dir . '/nexeng_hits.log';
    // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- Network drop-in (advanced-cache-network.php) executes before WP loads; WP_Filesystem is unavailable here.
    if ( is_dir( $log_dir ) || @mkdir( $log_dir, 0755, true ) ) {
        $htaccess = $log_dir . '/.htaccess';
        if ( ! file_exists( $htaccess ) ) {
            @file_put_contents( $htaccess, "Order deny,allow\nDeny from all\n" );
        }
        @file_put_contents( $log_file, $log_entry, FILE_APPEND );
    }

    exit;
})();
