<?php
/**
 * Nexora Engine — Advanced Cache Drop-In  (v__NEXENG_VERSION__)
 *
 * Auto-generated by Nexora Engine (NEXENG_Dropin::install()).
 * DO NOT EDIT MANUALLY — this file is overwritten whenever Static Site
 * Generation is toggled in the admin UI.
 *
 * Loaded by WordPress at the very top of wp-settings.php (when WP_CACHE
 * is true). If the request matches a captured SSG static file, we send
 * it and exit — WordPress never finishes booting. ~5–15 ms TTFB on
 * modern PHP with opcache enabled. Works universally on Apache, Nginx,
 * LiteSpeed, IIS — no server config required.
 *
 * @nexora-dropin
 * @signature 6f3a1c
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

$start_time = microtime(true);

if ( ! function_exists( 'nexeng_dropin_server' ) ) {
    /**
     * Read $_SERVER safely from inside the drop-in.
     *
     * This file is loaded from wp-settings.php before the rest of WordPress,
     * so sanitize_text_field() and wp_unslash() are not available here — hence
     * a plain-PHP equivalent rather than a call into the plugin's
     * NEXENG_Request helper.
     *
     * $_SERVER is attacker-controlled: every HTTP_* entry is a request header
     * verbatim, and REQUEST_URI and QUERY_STRING come straight off the request
     * line. Strip slashes if magic-quote-style escaping is in play, drop
     * control characters, and clip, so nothing that lands in a header, a log
     * line or a cache path can carry a newline or a NUL.
     *
     * @param string $key     Server key.
     * @param string $default Returned when absent or empty.
     * @param int    $max     Maximum length kept.
     * @return string
     */
    function nexeng_dropin_server( $key, $default = '', $max = 2048 ) {
        if ( ! isset( $_SERVER[ $key ] ) || ! is_scalar( $_SERVER[ $key ] ) ) {
            return $default;
        }
        $value = (string) $_SERVER[ $key ];
        if ( function_exists( 'get_magic_quotes_gpc' ) && @get_magic_quotes_gpc() ) {
            $value = stripslashes( $value );
        }
        // Remove C0/C1 control characters — newlines here mean header injection.
        $value = preg_replace( '/[\x00-\x1F\x7F-\x9F]/u', '', $value );
        if ( null === $value ) {
            // preg_replace returns null on invalid UTF-8; fall back to a byte-wise pass.
            $value = preg_replace( '/[\x00-\x1F\x7F]/', '', (string) $_SERVER[ $key ] );
        }
        $value = substr( (string) $value, 0, $max );
        return '' === $value ? $default : $value;
    }
}

if ( ! function_exists( 'nexeng_static_html_cache_control' ) ) {
    /**
     * Cache-Control for static HTML — tuned for real visitors, not lab scores.
     *
     * max-age=300               Repeat views load from the browser cache (5 min).
     * s-maxage=3600             CDN / reverse-proxy edges hold HTML for 1 hour.
     * stale-while-revalidate    Slow or flaky networks keep the last good page visible
     *                           while a background refresh runs (up to 24 hours).
     * must-revalidate + ETag    After max-age, the browser checks with the server;
     *                           rebuilds change the ETag so updates still land.
     */
    function nexeng_static_html_cache_control(): string {
        return 'public, max-age=300, s-maxage=3600, stale-while-revalidate=86400, must-revalidate';
    }
}

if ( ! function_exists( 'nexeng_static_runtime_sync_html' ) ) {
    function nexeng_static_runtime_sync_html( string $html, string $build_id, string $home_prefix ): string {
        if ( $build_id === '' ) {
            return $html;
        }

        $version_asset = static function ( array $m ) use ( $build_id ): string {
            $url = html_entity_decode( $m[3], ENT_QUOTES, 'UTF-8' );
            if ( preg_match( '#^(?:data|blob):#i', $url ) ) {
                return $m[0];
            }
            // phpcs:ignore WordPress.WP.AlternativeFunctions.parse_url_parse_url -- Drop-in (advanced-cache.php) executes before WordPress loads; wp_parse_url() is undefined here, so native parse_url() is required.
            $parts = parse_url( $url );
            $path  = is_array( $parts ) && isset( $parts['path'] ) ? (string) $parts['path'] : $url;
            if ( ! preg_match( '/\.(?:css|js)$/i', $path ) || strpos( $path, '/_ncx/' ) !== false ) {
                return $m[0];
            }
            $fragment = '';
            if ( strpos( $url, '#' ) !== false ) {
                [ $url, $fragment ] = explode( '#', $url, 2 );
                $fragment = '#' . $fragment;
            }
            $url = preg_replace( '/([?&])ver=[^&]*/i', '$1ver=' . rawurlencode( $build_id ), $url, 1, $count );
            if ( ! $count ) {
                $url .= ( strpos( $url, '?' ) === false ? '?' : '&' ) . 'ver=' . rawurlencode( $build_id );
            }
            return $m[1] . '=' . $m[2] . htmlspecialchars( str_replace( '?&', '?', $url ) . $fragment, ENT_QUOTES, 'UTF-8' ) . $m[2];
        };

        $html = preg_replace_callback( '/\b(href|src)=(["\'])([^"\']+\.(?:css|js)(?:\?[^"\']*)?)\2/i', $version_asset, $html );

        $meta = '<meta name="ncx-build" content="' . htmlspecialchars( $build_id, ENT_QUOTES, 'UTF-8' ) . '">';
        if ( preg_match( '/<meta[^>]+name=["\']ncx-build["\'][^>]*>/i', $html ) ) {
            $html = preg_replace( '/<meta[^>]+name=["\']ncx-build["\'][^>]*>/i', $meta, $html, 1 );
        } else {
            $html = preg_replace( '/(<\/head>)/i', $meta . '$1', $html, 1 );
        }

        $script = '<script id="ncx-runtime-sync">(function(){'
            . 'var b=' . json_encode( $build_id ) . ';'
            . 'try{localStorage.setItem("nexeng_build_id",b)}catch(e){}'
            . 'window.NEXENG_BUILD_ID=b;'
            . '})();</script>';

        // If a runtime-sync script is already present (baked in at capture time),
        // REPLACE it so its build ID matches the assets/meta we just re-versioned
        // to $build_id above. Bailing here left a stale build ID in the script
        // while the assets advanced — the SPA nav enhancer then saw a build
        // mismatch and could paint a page before its (newly-versioned) CSS
        // applied, i.e. the intermittent flash of unstyled layout.
        if ( strpos( $html, 'ncx-runtime-sync' ) !== false ) {
            $replacement = str_replace( [ '\\', '$' ], [ '\\\\', '\\$' ], $script );
            return preg_replace(
                '/<script id=["\']ncx-runtime-sync["\']>.*?<\/script>/is',
                $replacement,
                $html,
                1
            );
        }

        return preg_replace( '/(<\/head>)/i', $script . '$1', $html, 1 );
    }

    function nexeng_static_html_valid( string $html, string $build_id = '' ): bool {
        if ( strlen( $html ) < 200 || stripos( $html, '</html>' ) === false ) { return false; }
        if ( stripos( $html, '<html' ) === false && stripos( $html, '<!doctype' ) === false ) { return false; }
        if ( $build_id !== '' && strpos( $html, 'name="ncx-build"' ) === false ) { return false; }
        return true;
    }

    function nexeng_static_variant_path( string $static_root, string $real_file, string $build_id, int $mtime ): string {
        $root = rtrim( str_replace( '\\', '/', $static_root ), '/' );
        $file = str_replace( '\\', '/', $real_file );
        $rel  = ltrim( substr( $file, strlen( $root ) ), '/' );
        $key  = substr( md5( $rel . '|' . $build_id . '|' . $mtime ), 0, 16 );
        return dirname( $static_root ) . '/nexora-private/ncx-sync/' . $key . '.html';
    }

    function nexeng_static_cleanup_variants( string $static_root ): void {
        $dir = dirname( $static_root ) . '/nexora-private/ncx-sync';
        // phpcs:ignore WordPress.WP.AlternativeFunctions.rand_mt_rand -- Drop-in runs before WP loads pluggable.php, so wp_rand() is unavailable; only a non-cryptographic 1-in-100 sampling probe.
        if ( ! is_dir( $dir ) || mt_rand( 1, 100 ) !== 1 ) { return; }
        $now = time();
        foreach ( glob( $dir . '/*' ) ?: [] as $file ) {
            if ( is_file( $file ) && ( substr( $file, -4 ) === '.tmp' || $now - (int) @filemtime( $file ) > 172800 ) ) {
                // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here.
                @unlink( $file );
            }
        }
    }

    function nexeng_static_synchronized_body( string $static_root, string $real_file, string $build_id, string $home_prefix, int $mtime ) {
        $variant = nexeng_static_variant_path( $static_root, $real_file, $build_id, $mtime );
        if ( is_file( $variant ) && (int) @filemtime( $variant ) >= $mtime ) {
            $cached = @file_get_contents( $variant );
            if ( is_string( $cached ) && nexeng_static_html_valid( $cached, $build_id ) ) {
                return $cached;
            }
        }

        $source = @file_get_contents( $real_file );
        if ( ! is_string( $source ) || ! nexeng_static_html_valid( $source ) ) { return false; }
        $synced = nexeng_static_runtime_sync_html( $source, $build_id, $home_prefix );
        if ( ! nexeng_static_html_valid( $synced, $build_id ) ) { return false; }

        $dir = dirname( $variant );
        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here.
        if ( ! is_dir( $dir ) ) { @mkdir( $dir, 0755, true ); }
        if ( is_dir( $dir ) ) {
            $deny = dirname( $dir ) . '/.htaccess';
            if ( ! file_exists( $deny ) ) { @file_put_contents( $deny, "Order deny,allow\nDeny from all\n" ); }
            // phpcs:ignore WordPress.WP.AlternativeFunctions.rand_mt_rand -- Drop-in runs before WP loads pluggable.php; mt_rand() only salts a temp filename, no security dependence.
            $tmp = $variant . '.tmp.' . substr( md5( microtime( true ) . mt_rand() ), 0, 8 );
            if ( @file_put_contents( $tmp, $synced, LOCK_EX ) !== false ) {
                // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here. Atomic variant publish.
                @rename( $tmp, $variant );
                // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_touch -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here.
                @touch( $variant, max( time(), $mtime ) );
            } else {
                // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here.
                @unlink( $tmp );
            }
        }
        nexeng_static_cleanup_variants( $static_root );
        return $synced;
    }
}

(function () use ( $start_time ) {

    // ─── Fast skip checks (cheapest first) ───────────────────────────────────

    // 0. Master kill switch.
    //
    // Static Delivery can be switched off in wp-admin, but that setting lives in
    // an option and this file runs before WordPress loads, so get_option() does
    // not exist here. Without a filesystem signal the drop-in kept serving the
    // mirror to anonymous visitors after the feature had been turned off — the
    // toggle appeared to do nothing.
    //
    // The marker is a "disabled" flag rather than an "enabled" one so that its
    // absence means serve: an existing install upgrading to this version has no
    // marker and keeps working, instead of going dark until someone re-toggles.
    if ( @is_file( '__NEXENG_PRIVATE_DIR__/ssg-disabled.flag' ) ) { return; }

    // 1. GET only.
    if ( 'GET' !== nexeng_dropin_server( 'REQUEST_METHOD', 'GET', 10 ) ) { return; }

    // 2. Any query string disables the cache, except Nexora's own
    // synchronization recovery probe.
    $query_string = nexeng_dropin_server( 'QUERY_STRING' );
    if ( $query_string !== '' && ! preg_match( '/^nexeng_sync=[a-z0-9]+$/i', $query_string ) ) { return; }

    // 3. Skip authenticated users — they need fresh nonces, admin bar, etc.
    if ( ! empty( $_COOKIE ) ) {
        foreach ( $_COOKIE as $k => $v ) {
            if ( strncmp( $k, 'wordpress_logged_in_', 20 ) === 0 ) { return; }
            if ( strncmp( $k, 'wp-postpass_',          12 ) === 0 ) { return; }
            if ( strncmp( $k, 'comment_author_',       15 ) === 0 ) { return; }
            if ( strncmp( $k, 'woocommerce_items_in_cart', 25 ) === 0 ) { return; }
            if ( $k === 'wp_woocommerce_session_' ) { return; }
        }
    }

    // 4. Resolve URI.
    // phpcs:ignore WordPress.WP.AlternativeFunctions.parse_url_parse_url -- Drop-in executes before WordPress loads; wp_parse_url() is undefined here, native parse_url() required.
    $uri = parse_url( nexeng_dropin_server( 'REQUEST_URI', '/' ), PHP_URL_PATH );
    if ( ! is_string( $uri ) || $uri === '' ) { return; }

    // 5. High-Speed Asset Streamer (Stealth + Speed)
    // Intercepts requests for cloaked assets (CSS, JS, Images) and serves them
    // immediately without booting WordPress. Works on Nginx fallback.
    if ( strpos( $uri, '/_ncx_v12/' ) !== false ) {
        $asset_mode   = '__NEXENG_ASSET_MODE__';
        $proxy_prefix = '__NEXENG_PROXY_PREFIX__';

        // Reverse-map the cloaked path back to the filesystem.
        $asset_path = null;
        $map = [
            '/_ncx_v12/assets/ep/'          => '__NEXENG_CONTENT_REL__/plugins/elementor-pro/',
            '/_ncx_v12/assets/e/'           => '__NEXENG_CONTENT_REL__/plugins/elementor/',
            '/_ncx_v12/assets/t/'           => '__NEXENG_CONTENT_REL__/themes/',
            '/_ncx_v12/assets/uploads/ncx/' => '__NEXENG_CONTENT_REL__/uploads/elementor/',
            '/_ncx_v12/assets/'             => '__NEXENG_CONTENT_REL__/',
            '/_ncx_v12/lib/'                => '__NEXENG_INC_REL__/',
        ];

        foreach ( $map as $virtual => $real ) {
            if ( strpos( $uri, $virtual ) !== false ) {
                $rel_path   = substr( $uri, strpos( $uri, $virtual ) + strlen( $virtual ) );
                $asset_path = ABSPATH . $real . $rel_path;
                break;
            }
        }

        if ( $asset_path && is_file( $asset_path ) ) {
            $real_asset = realpath( $asset_path );
            // Path-traversal guard: resolved path must remain inside ABSPATH.
            // Normalize directory separators — realpath() returns backslashes on Windows
            // while ABSPATH may contain forward slashes (dirname + '/').
            $_nexeng_abspath_fwd = rtrim( str_replace( '\\', '/', ABSPATH ), '/' );
            if ( $real_asset && strncmp( str_replace( '\\', '/', $real_asset ), $_nexeng_abspath_fwd . '/', strlen( $_nexeng_abspath_fwd ) + 1 ) !== 0 ) {
                $real_asset = false;
            }
            if ( $real_asset ) {
                $ext = strtolower( pathinfo( $real_asset, PATHINFO_EXTENSION ) );
                $mimes = [
                    'css'   => 'text/css',
                    'js'    => 'application/javascript',
                    'png'   => 'image/png',
                    'jpg'   => 'image/jpeg',
                    'jpeg'  => 'image/jpeg',
                    'gif'   => 'image/gif',
                    'svg'   => 'image/svg+xml',
                    'webp'  => 'image/webp',
                    'ico'   => 'image/x-icon',
                    'woff'  => 'font/woff',
                    'woff2' => 'font/woff2',
                    'ttf'   => 'font/ttf',
                    // ── Video / Audio ─────────────────────────────────────────
                    'mp4'   => 'video/mp4',
                    'webm'  => 'video/webm',
                    'ogv'   => 'video/ogg',
                    'mov'   => 'video/quicktime',
                    'mp3'   => 'audio/mpeg',
                    'wav'   => 'audio/wav',
                    'ogg'   => 'audio/ogg',
                    'm4a'   => 'audio/mp4',
                    // ── Documents ────────────────────────────────────────────
                    'pdf'   => 'application/pdf',
                ];
                $mime = $mimes[ $ext ] ?? 'application/octet-stream';

                @header_remove( 'X-Powered-By' );
                header( 'Content-Type: ' . $mime );
                header( 'Cache-Control: public, max-age=31536000, immutable' );
                header( 'X-Nexora-Asset: HIT' );

                // If CSS/JS, we must mask internal URLs (e.g. background-image)
                if ( ( $ext === 'css' || $ext === 'js' ) && $asset_mode === 'proxy' ) {
                    $body = file_get_contents( $real_asset );
                    
                    // Basic replacements for internal assets.
                    $home = '__NEXENG_HOME_PREFIX__';
                    $body = str_replace( '/__NEXENG_CONTENT_REL__/',   $home . $proxy_prefix . '/_ncx_v12/assets/', $body );
                    $body = str_replace( '/__NEXENG_INC_REL__/',  $home . $proxy_prefix . '/_ncx_v12/lib/',    $body );
                    
                    // Path compression (ep, e, t, uploads/ncx)
                    $body = str_replace( '/_ncx_v12/assets/plugins/elementor-pro/', '/_ncx_v12/assets/ep/', $body );
                    $body = str_replace( '/_ncx_v12/assets/plugins/elementor/',     '/_ncx_v12/assets/e/',  $body );
                    $body = str_replace( '/_ncx_v12/assets/themes/',                '/_ncx_v12/assets/t/',  $body );
                    $body = str_replace( '/_ncx_v12/assets/uploads/elementor/',     '/_ncx_v12/assets/uploads/ncx/', $body );

                    // Dynamic endpoints. The admin-ajax path is baked in at
                    // install time from admin_url(), because wp-admin can be
                    // relocated and this file runs before admin_url() exists.
                    $body = str_replace( '__NEXENG_AJAX_PATH__', $proxy_prefix . '/_ncx/aj',   $body );
                    $body = str_replace( '/wp-json/',                $proxy_prefix . '/_ncx/api/', $body );

                    // Namespace renames.
                    $body = str_replace( 'window.wp', 'window.ncx', $body );
                    $body = str_replace( 'wp.i18n',   'ncx.i18n',   $body );
                    $body = str_replace( 'wp.hooks',  'ncx.hooks',  $body );

                    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Drop-in serve path: $body is the cached static HTML page being streamed to the browser; it is intentional full-page HTML and must be emitted verbatim (escaping would render markup as visible text).
                    echo $body;
                } else {
                    // ── Range request support (video / audio seeking) ─────────
                    // Browsers issue Range requests to seek in video/audio files.
                    // Without this, videos pause/fail when the user scrubs forward.
                    $file_size = filesize( $real_asset );
                    $start     = 0;
                    $end       = $file_size - 1;
                    $range     = trim( nexeng_dropin_server( 'HTTP_RANGE', '', 256 ) );

                    if ( $range && preg_match( '/^bytes=(\d*)-(\d*)$/', $range, $rm ) ) {
                        // Parse range.
                        if ( $rm[1] === '' ) {
                            // Suffix range: bytes=-N means last N bytes.
                            $start = max( 0, $file_size - (int) $rm[2] );
                        } else {
                            $start = (int) $rm[1];
                            $end   = $rm[2] !== '' ? min( (int) $rm[2], $file_size - 1 ) : $file_size - 1;
                        }
                        if ( $start > $end || $start >= $file_size ) {
                            http_response_code( 416 );
                            header( 'Content-Range: bytes */' . $file_size );
                            exit;
                        }
                        http_response_code( 206 );
                        header( 'Content-Range: bytes ' . $start . '-' . $end . '/' . $file_size );
                        header( 'Accept-Ranges: bytes' );
                        header( 'Content-Length: ' . ( $end - $start + 1 ) );
                        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here. Range-request streaming needs a native handle.
                        $fp = @fopen( $real_asset, 'rb' );
                        if ( $fp ) {
                            fseek( $fp, $start );
                            $rem = $end - $start + 1;
                            while ( $rem > 0 && ! feof( $fp ) ) {
                                // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fread -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here. Range-request streaming.
                                $buf = fread( $fp, min( 65536, $rem ) );
                                if ( false === $buf ) { break; }
                                echo $buf; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
                                $rem -= strlen( $buf );
                            }
                            // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here.
                            fclose( $fp );
                        }
                        exit;
                    }

                    header( 'Accept-Ranges: bytes' );
                    header( 'Content-Length: ' . $file_size );
                    // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_readfile -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here. Streams an asset on the serve path.
                    readfile( $real_asset );
                }
                exit;
            }
        }
    }

    // 6. Skip WP system / API / admin paths.
    if ( preg_match(
        '#^(?:/[^/]+)?/(wp-admin|wp-login\.php|wp-cron\.php|wp-json|wp-content|wp-includes|xmlrpc\.php)#i',
        $uri
    ) ) { return; }

    // 7. Skip URLs with file extensions (Standard pages shouldn't have them).
    if ( preg_match( '#\.[a-zA-Z0-9]{2,5}$#', $uri ) ) { return; }

    // ─── Resolve target file ─────────────────────────────────────────────────

    // Static root injected at install time (absolute path on disk).
    // Normalise to forward slashes immediately — wp_get_upload_dir() can return
    // mixed backslash/forward-slash paths on Windows XAMPP environments.
    $static_root = str_replace( '\\', '/', '__NEXENG_STATIC_ROOT__' );
    if ( $static_root === '' || ! is_dir( $static_root ) ) { return; }

    // Strip subdirectory install prefix from URI before lookup.
    $home_prefix = '__NEXENG_HOME_PREFIX__';
    if ( $home_prefix !== '' && strpos( $uri, $home_prefix ) === 0 ) {
        $uri = substr( $uri, strlen( $home_prefix ) );
        if ( $uri === '' ) { $uri = '/'; }
    }

    $slug = trim( $uri, '/' );
    $file = $slug === ''
        ? $static_root . '/index.html'
        : $static_root . '/' . $slug . '/index.html';

    // Path-traversal guard — normalise directory separators for cross-platform use.
    // realpath() returns backslashes on Windows; convert both sides to forward slashes
    // so the comparison is consistent on every OS. Also require a separator after the
    // root so "/nexora-staticBAD/..." cannot spoof "/nexora-static".
    $real_root = realpath( $static_root );
    $real_file = realpath( $file );
    if ( ! $real_root || ! $real_file ) { return; }
    $_nexeng_fwd_root = rtrim( str_replace( '\\', '/', $real_root ), '/' );
    $_nexeng_fwd_file = str_replace( '\\', '/', $real_file );
    if ( strncmp( $_nexeng_fwd_file, $_nexeng_fwd_root . '/', strlen( $_nexeng_fwd_root ) + 1 ) !== 0 ) { return; }
    if ( ! is_file( $real_file ) ) { return; }

    // ─── Conditional response (304) ──────────────────────────────────────────

    $mtime         = (int) filemtime( $real_file );
    $manifest_file = $static_root . '/manifest.json';
    $build_id      = 'nexeng_build_' . $mtime;
    if ( is_file( $manifest_file ) ) {
        $manifest_raw = @file_get_contents( $manifest_file );
        $manifest     = is_string( $manifest_raw ) ? json_decode( $manifest_raw, true ) : null;
        if ( is_array( $manifest ) && ! empty( $manifest['build_id'] ) ) {
            $build_id = preg_replace( '/[^a-zA-Z0-9_\-]/', '', (string) $manifest['build_id'] );
        }
    }
    $body          = nexeng_static_synchronized_body( $static_root, $real_file, $build_id, $home_prefix, $mtime );
    if ( ! is_string( $body ) ) { return; }
    $etag          = '"ncx-' . substr( md5( $body ), 0, 16 ) . '"';
    $last_modified = gmdate( 'D, d M Y H:i:s', $mtime ) . ' GMT';

    $client_etag = isset( $_SERVER['HTTP_IF_NONE_MATCH'] )     ? trim( nexeng_dropin_server( 'HTTP_IF_NONE_MATCH', '', 256 ) )     : '';
    $client_lm   = isset( $_SERVER['HTTP_IF_MODIFIED_SINCE'] ) ? trim( nexeng_dropin_server( 'HTTP_IF_MODIFIED_SINCE', '', 128 ) ) : '';

    // Nginx gzip/brotli compression weakens strong ETags: "ncx-..." → W/"ncx-..."
    // Strip the W/ prefix before comparing so the 304 path fires correctly even
    // when the client sends back the weakened ETag it received from a compressed 200.
    $norm_client_etag = ( strncmp( $client_etag, 'W/', 2 ) === 0 ) ? substr( $client_etag, 2 ) : $client_etag;

    if ( $norm_client_etag === $etag ) {
        http_response_code( 304 );
        header( 'ETag: ' . $etag );
        header( 'Last-Modified: ' . $last_modified );
        // Refresh the browser's cache-control window so a revalidated page
        // gets another full max-age before the next conditional check.
        header( 'Cache-Control: ' . nexeng_static_html_cache_control() );
        header( 'X-Robots-Tag: index, follow', true );
        header( 'X-Nexora-Cache: REVALIDATED' );
        exit;
    }

    // ─── 200 OK — stream the static file ─────────────────────────────────────

    // Stealth headers — keep parity with shell-template.php so the site
    // appears as a Next.js / CDN deployment to fingerprinting tools.
    @header_remove( 'X-Powered-By' );
    @header_remove( 'X-Pingback' );
    @header_remove( 'Link' );
    // Remove any X-Robots-Tag set by WordPress or upstream code before we got here.
    // (Server-level Nginx headers cannot be removed from PHP — fix those in server config.)
    @header_remove( 'X-Robots-Tag' );

    header( 'Content-Type: text/html; charset=UTF-8' );
    header( 'Content-Length: ' . strlen( $body ) );
    header( 'ETag: ' . $etag );
    header( 'Last-Modified: ' . $last_modified );
    // ── Cache strategy (see nexeng_static_html_cache_control()) ─────────────────
    header( 'Cache-Control: ' . nexeng_static_html_cache_control() );
    header( 'Vary: Accept-Encoding' );
    header( 'X-Nexora-Cache: HIT' );
    header( 'X-Nexora-Delivery: static' );
    header( 'X-Powered-By: Next.js' );
    header( 'X-Nextjs-Cache: HIT' );

    // ── Security headers — must match NEXENG_Hardening::send_security_headers()
    //    so cached pages and PHP-rendered pages have identical protection.
    header( 'X-Frame-Options: SAMEORIGIN' );
    header( 'X-Content-Type-Options: nosniff' );
    header( 'Referrer-Policy: strict-origin-when-cross-origin' );
    header( 'X-Robots-Tag: index, follow', true );

    // Build log entry before streaming (timestamp accuracy).
    // Sanitize attacker-controlled fields before writing to log.
    $raw_ua    = nexeng_dropin_server( 'HTTP_USER_AGENT', '', 255 );
    $clean_ua  = preg_replace( '/[^\x20-\x7E]/', '', $raw_ua ); // printable ASCII only
    $clean_ua  = substr( $clean_ua, 0, 200 );                   // cap length
    $log_entry = json_encode( [
        'url'        => $uri,
        'hit_type'   => 'hit',
        // max(1,...) prevents 0ms on Windows where microtime() has ~1ms resolution.
        // A sub-millisecond cache hit rounds to <1ms, not "no data".
        'ttfb'       => max( 1, (int) round( ( microtime( true ) - $start_time ) * 1000 ) ),
        'ip'         => nexeng_dropin_server( 'REMOTE_ADDR', '', 45 ),
        'ua'         => $clean_ua,
        'ts'         => time(),
    ] ) . "\n";

    // Stream static file to client FIRST — log write must not block TTFB.
    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Drop-in serve path: $body is the cached static HTML page streamed verbatim to the browser; intentional full-page HTML, escaping would break it.
    echo $body;

    // Flush PHP output buffer + system write buffer so bytes reach the client
    // before the (cheap) file write below.
    @ob_flush();
    flush();

    // Non-blocking log write. Store in a private subdirectory protected by
    // .htaccess so the log is not publicly downloadable (GDPR / security).
    // Baked in at install time from wp_upload_dir(): the uploads directory is
    // configurable, WP_CONTENT_DIR can point anywhere, and on multisite each
    // site has its own - none of which this file can work out for itself,
    // because it runs before WordPress loads.
    $log_dir  = '__NEXENG_PRIVATE_DIR__';
    $log_file = $log_dir . '/nexeng_hits.log';
    // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir -- Drop-in (advanced-cache.php) executes before WP loads; WP_Filesystem is unavailable here.
    if ( is_dir( $log_dir ) || @mkdir( $log_dir, 0755, true ) ) {
        // Write a deny-all .htaccess on first use.
        $htaccess = $log_dir . '/.htaccess';
        if ( ! file_exists( $htaccess ) ) {
            @file_put_contents( $htaccess, "Order deny,allow\nDeny from all\n" );
        }
        @file_put_contents( $log_file, $log_entry, FILE_APPEND );
    }

    exit;
})();
